services:
  - type: web
    name: ai-resume-generator-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: GEMINI_API_KEY
        sync: false
      - key: MUSE_API_KEY
        sync: false
